### ISSUE TITLE
Transifex doesn't work with Django 4.0 or later.

### ISSUE THREAD

**Issue by nedamoeini1370** [transifex/transifex-python#98]
Hi Transifex team,
We have a project on Django=4.1. added Transifex to my project, I received the error below. It seems the package does not support Django>=4.0 since based on the django 4.0 [release note](https://docs.djangoproject.com/en/4.1/releases/4.0/): **"The undocumented TRANSLATOR_COMMENT_MARK constant is moved from django.template.base to django.utils.translation.template."**

ImportError: cannot import name 'TRANSLATOR_COMMENT_MARK' from 'django.template.base' (/usr/local/lib/python3.9/site-packages/django/template/base.py)

Could you please consider my request to support Django>=4.0?

This is my traceback:

$ python src/manage.py transifex push
Traceback (most recent call last):
  File "/opt/project/core/src/manage.py", line 97, in <module>
    main()
  File "/opt/project/core/src/manage.py", line 93, in main
    manager.main()
  File "/opt/project/core/src/manage.py", line 87, in main
    execute_from_command_line(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 279, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 48, in load_command_class
    module = import_module("%s.management.commands.%s" % (app_name, name))
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/site-packages/transifex/native/django/management/commands/transifex.py", line 5, in <module>
    from transifex.native.django.management.utils.migrate import Migrate
  File "/usr/local/lib/python3.9/site-packages/transifex/native/django/management/utils/migrate.py", line 11, in <module>
    from transifex.native.django.tools.migrations.templatetags import \
  File "/usr/local/lib/python3.9/site-packages/transifex/native/django/tools/migrations/templatetags.py", line 10, in <module>
    from django.template.base import TRANSLATOR_COMMENT_MARK, DebugLexer, Parser
ImportError: cannot import name 'TRANSLATOR_COMMENT_MARK' from 'django.template.base' (/usr/local/lib/python3.9/site-packages/django/template/base.py)

Thank you!

**Comment by nbasili** [comment]
Some initial effort has started here: https://github.com/transifex/transifex-python/pull/102

**Comment by nbasili** [comment]
@nedamoeini1370  It should be working now on `transifex-python==3.2.0`, can you please verify it's working on your project?

**Comment by nedamoeini1370** [comment]
> @nedamoeini1370 It should be working now on `transifex-python==3.2.0`, can you please verify it's working on your project?

Thank you for adding the Django 4.0 support. I'll check it and let you know soon.

**Comment by nbasili** [comment]
I am closing this issue as resolved. If for any reason there are still issues, feel free to reopen.
